app/models.py
from dataclasses import dataclass
from app.extensions import db
from enum import IntEnum


@dataclass
class User(db.Model):
    __tablename__ = 'user'
    id: int
    login: str
    email: str
    password: str
    role: str
    has_token: bool
    has_additional_info: bool
    additional_info: dict

    id = db.Column(db.Integer, primary_key=True)
    login = db.Column(db.Text, unique=True)
    email = db.Column(db.Text, unique=True)
    password = db.Column(db.Text)
    role = db.Column(db.Text, nullable=False, default='user')
    has_token = db.Column(db.Boolean, default=False)
    has_additional_info = db.Column(db.Boolean, default=False)
    additional_info = db.Column(db.JSON, default='')


@dataclass
class Diary(db.Model):
    __tablename__ = 'diary'
    id: int
    user_id: int
    school_id: int
    content_json: dict

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer)
    school_id = db.Column(db.Integer)
    content_json = db.Column(db.JSON)

@dataclass
class Subject(db.Model):
    id: int
    name: str

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)


Weekdays = IntEnum('Weekdays', 'sun mon tue wed thu fri sat', start=0)


@dataclass
class Day(db.Model):
    id: int
    diary_id: int
    week_day: Weekdays
    subjects: dict

    id = db.Column(db.Integer, primary_key=True)
    diary_id = db.Column(db.Integer)
    week_day = db.Column(db.Integer)
    subjects = db.Column(db.JSON)

app/forms.py
from app.extensions import FlaskForm, bcrypt
from wtforms import BooleanField, StringField, PasswordField, ValidationError, SubmitField
from wtforms.validators import Length, Email, DataRequired, EqualTo
from app import db
from app.models import User

class RegistrationForm(FlaskForm):
    username = StringField('Имя пользователя', [Length(min=4, max=20), DataRequired()])
    email = StringField('Email-адрес', [Email(), DataRequired()])
    password = PasswordField('Новый пароль', [
        Length(min=6),
        DataRequired(),
        EqualTo('confirm', message='Пароли должны совпадать')
    ])
    confirm = PasswordField('Повторите пароль', [DataRequired()])
    accept_policy = BooleanField('Я принимаю условия и ставлю за семестровую макс балл', [DataRequired()])
    remember_me = BooleanField('Запомнить меня')
    submit = SubmitField(label=('Submit'))

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Данный email уже занят.')

    def validate_username(self, username):
        user = User.query.filter_by(email=username.data).first()
        if user:
            raise ValidationError('Этот юзернейм уже занят.')

class LoginForm(FlaskForm):
    email = StringField('Email-адрес', [Email(), DataRequired()])
    password = PasswordField('Ваш пароль', [
        DataRequired()
    ])
    remember_me = BooleanField('Запомнить меня')
    submit = SubmitField(label=('Submit'))

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if not user:
            raise ValidationError('Неверный email.')

    def validate_password(self, password):
        user = User.query.filter_by(email=self.email.data).first()
        if not user or not bcrypt.check_password_hash(user.password, password.data):
            raise ValidationError('Неверный пароль.')


class ForgotPasswordForm(FlaskForm):
    email = StringField('Email-адрес', [Email(), DataRequired()])
    submit = SubmitField(label=('Submit'))

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if not user:
            raise ValidationError('Неверный email.')

class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', [DataRequired()])
    confirm = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Request Password Reset')

app/__init__.py
from flask import Flask

from config import Config
from app.extensions import db, api, csrf, session, bcrypt, socketio, mail, admin


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    # Initialize Flask extensions here
    db.init_app(app)
    session.init_app(app)
    api.init_app(app)
    csrf.init_app(app)
    bcrypt.init_app(app)
    socketio.init_app(app)
    mail.init_app(app)
    admin.init_app(app)

    from app.static.ws import register_socket_handlers
    register_socket_handlers(socketio)

    # Register blueprints here
    from app.routes.admin import register_admin_views
    register_admin_views()

    from app.routes.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.routes.auth import bp as login_bp
    app.register_blueprint(login_bp, url_prefix='/auth')

    from app.routes.diary import bp as diary_bp
    app.register_blueprint(diary_bp, url_prefix='/school-diary')

    from app.routes.profile import bp as profile_bp
    app.register_blueprint(profile_bp, url_prefix='/profile')

    @app.route('/test/')
    def test_page():
        return '<h1>Testing the Flask Application Factory Pattern</h1>'

    return app

app/routes/admin/__init__.py
from app.extensions import admin, db
from app.models import User, Diary, Subject
from flask_admin.contrib.sqla import ModelView
from flask import redirect, url_for, session

class View(ModelView):
    def is_accessible(self):
        print('admin wanna to enter' ,session.get('uid'))
        if session.get('user_id'):
            user = User.query.filter_by(id=session.get('user_id')).first()
            print(user)
            if user:
                print(user.role == 'site-admin')
                return user.role == 'site-admin'
            return False
        else:
            print('you are not admin')
            return False

    def inaccessible_callback(self, name, **kwargs):
        # redirect to login page if user doesn't have access
        return redirect(url_for('auth.login'))


def register_admin_views():
    admin.add_view(View(User, db.session, name='User'))
    admin.add_view(View(Diary, db.session, name='Diary'))
    admin.add_view(View(Subject, db.session, name='Subject'))

app/routes/diary/__init__.py
from flask import Blueprint

bp = Blueprint('school-diary', __name__)

from app.routes.diary import routes

app/routes/diary/routes.py
from flask import render_template, redirect, url_for, session
from app.routes.diary import bp
from app.models import User

@bp.route('/')
def index():
    return render_template('diary/index.jinja2')

app/routes/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.routes.main import routes

app/routes/main/routes.py
from flask import render_template, redirect, url_for, session
from app.routes.main import bp
from app.models import User

@bp.route('/')
def index():
    uid = session.get('user_id')
    user = User.query.filter_by(id=uid).first()
    if session.get('authorized') and user:
        match user.role:
            case 'teacher':
                return render_template('', user=user)
            case 'student':
                return render_template('index.jinja2', navlinks=[('school-diary', 'строница дневника')], user=user)
            case 'principal':
                return render_template('index.jinja2', user=user)
            case 'site-admin':
                return render_template('index.jinja2', navlinks=[('admin', 'Admin page'), ('school-diary', 'строница дневника')], user=user)
            case _:
                return render_template('index.jinja2', user=user)
    return redirect(url_for('auth.login'))

app/routes/profile/__init__.py
from flask import Blueprint

bp = Blueprint('profile', __name__)

from app.routes.profile import routes

app/routes/profile/routes.py
from flask import render_template, redirect, url_for, session
from app.routes.profile import bp
from app.models import User

@bp.route('/')
def index():
    user = User.query.filter_by(id=session.get('user_id')).first()
    return render_template('profile/index.jinja2', user=user)

app/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %} {% endblock %} - семестровка</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/base.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
        integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
        integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ"
        crossorigin="anonymous"></script>

<main>
    <div class="container">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">

            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{{ url_for('profile.index') }}">My profile</a> </li>
                {% for link, linkname in navlinks %}
                    <li class="nav-item"><a class="nav-link active" aria-current="page"
                                            href="{{ url_for(link+'.index') }}">{{ linkname }}</a></li>
                {% endfor %}
            </ul>

            <div class="col-md-3 text-end">
                {% if session.get('authorized') %}
                    <a href='{{ url_for('auth.logout') }}' class="btn btn-primary">Log out</a>
                {% else %}
                    <a href='{{ url_for('auth.login') }}' class="btn btn-outline-primary me-2">Login</a>
                    <a href='{{ url_for('auth.signup') }}' class="btn btn-primary">Sign-up</a>
                {% endif %}
            </div>
        </header>
    </div>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</main>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"
        integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA=="
        crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf-8">
    var socket = io();
</script>
<script src={{ url_for('static', filename='js/ws.js') }}></script>
</body>
</html>

app/templates/diary/index.jinja2
{% extends 'base.jinja2' %}

{% block content %}
    <span class="title"><h1>{% block title %} Мой дневник {% endblock %}</h1></span>
    <div class="content">
        <div class="diary">
            {% for diary_elem in diary %}
                <div class="day">
                    {% for subject in diary_elem.subjects %}
                        <div class="subject">
                            <div class="subject-name"></div>
                            <div class="homework"></div>
                            <div class="grade"></div>
                            <div class="teacher"></div>
                            <div class="classroom-number"></div>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/index.jinja2
{% extends 'base.jinja2' %}

{% block content %}
    <span class="title"><h1>{% block title %} Главная страница {% endblock %}</h1></span>
    <div class="content">
        <h1>Тут чёто умное</h1>
    </div>
{% endblock %}

app/templates/profile/index.jinja2
{% extends 'base.jinja2' %}

{% block content %}
    {% if user %}
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="d-flex">
                        <div class="img-thumbnail">
                            {% if user.has_additional_info %}
                                <img src="{{ user.additional_info['avatar_url'] }}">
                            {% else %}
                                <svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" fill="currentColor"
                                     class="bi bi-image"
                                     viewBox="0 0 16 16">
                                    <path d="M6.002 5.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                                    <path d="M2.002 1a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2h-12zm12 1a1 1 0 0 1 1 1v6.5l-3.777-1.947a.5.5 0 0 0-.577.093l-3.71 3.71-2.66-1.772a.5.5 0 0 0-.63.062L1.002 12V3a1 1 0 0 1 1-1h12z"/>
                                </svg>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <div class="accordion accordion-flush" id="accordionFlushExample">
                                <div class="accordion-item">
                                    <h2 class="accordion-header">
                                        <button class="accordion-button collapsed" type="button"
                                                data-bs-toggle="collapse" data-bs-target="#flush-collapseOne"
                                                aria-expanded="false" aria-controls="flush-collapseOne">
                                            Additional user info
                                        </button>
                                    </h2>
                                    <div id="flush-collapseOne" class="accordion-collapse collapse"
                                         data-bs-parent="#accordionFlushExample">
                                        <div class="accordion-body">
                                            <div class="accordion-item">
                                                <ul class="list-group list-group-flush">
                                                    {% if user.has_additional_info %}
                                                        {% for key, value in user.additional_info.items() %}
                                                            {% if value %}
                                                                <li class="list-group-item">{{ key }}: {{ value }}</li>
                                                            {% endif %}
                                                        {% endfor %}
                                                    {% endif %}
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                            </div>
                            <div class="card-body">
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item">User role: {{ user.role }}</li>
                                    <li class="list-group-item">User email: {{ user.email }}</li>
                                    <li id="username_field" class="list-group-item">User name: {{ user.login }}</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="card mt-2">
                        <div class="card-body">
                            <a class="btn btn-outline-primary" href="#" role="button">Сменить почту</a>
                            <span class="btn btn-outline-primary btn-file">Сменить аву<input type="file"></span>
                            <button id="change_login" class="btn btn-outline-primary"  role="button">Сменить логин</button>
                            <a class="btn btn-outline-warning" href="{{ url_for('auth.forgot_password') }}" role="button">Сбросить пароль</a>
                            <a class="btn btn-outline-danger" href="#" role="button">Удалить аккаунт</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

app/templates/student/diary.jinja2
{% extends 'base.jinja2' %}

{% block content %}

{% endblock %}